### ISSUE TITLE
Cordova plugin

### ISSUE THREAD

**Issue by davistan** [MOLPay/Mobile_SDK-Android#11]
Hi, have you any intention to create a Cordova plugin based on your SDK?

**Comment by natsu90** [comment]
+1 for this

**Comment by tekjau** [comment]
Hi all, cordova or hybrid plugin or JS sdk will be available in first quarter of 2016 if nothing goes wrong

**Comment by natsu90** [comment]
23 days to go

**Comment by clewlb** [comment]
@natsu90,
ETA for this product is early April 2016. Please stay tune with us, and thank you for your support.

**Comment by clewlb** [comment]
@natsu90, @davistan,
We have released our sdk for Cordova. Please check it out. https://github.com/MOLPay/molpay-mobile-xdk-cordova.

**Comment by davistan** [comment]
Thanks and great job!
