### ISSUE TITLE
white screen if select CIMB in v5.1.3

### ISSUE THREAD

**Issue by azizimusa** [MOLPay/Mobile_SDK-Android#13]
In logcat :

> com.skoolsaf W/AwContents: nativeOnDraw failed; clearing to background color.
com.skoolsaf I/chromium: [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
com.skoolsaf I/chromium: [INFO:CONSOLE(176)] "Uncaught TypeError: Cannot read property 'contentWindow' of null", source: https://www.cimbclicks.com.my/TIBSEPWeb/index.jsp (176)
com.skoolsaf D/onPageFinished: https://www.cimbclicks.com.my/TIBSEPWeb/index.jsp

After several attempt. CIMB page does appear, but only to watch the progress spinner is spin endlessly.

**Comment by clewlb** [comment]
@azizimusa,
Please upgrade to our latest android sdk, https://github.com/MOLPay/molpay-mobile-xdk-android. Thanks.
