### ISSUE TITLE
What could be the issue the payment method selection keeps loading?

### ISSUE THREAD

**Issue by edwinkoh1989** [MOLPay/Mobile_SDK-Android#5]
It's an enquiry BTW, it's very odd that I have been getting non-stop loading once I selected payment method function in MOL Pay page.

I have make sure that I am passing in the right 5 pieces of information into the SDK.

**Comment by tekjau** [comment]
Do you have a dev account credentials? If not probably you need to request from support@molpay.com before you can test it (must have api username/password and with your app name registered)

**Comment by mqadhavi** [comment]
I think if the credential wrong to access the API/web service, its should return the error from the API to the android client.
and i suggest set timeout from in httpconection from android client, so if long time respond from API or connection problem, its will close.
IMHO

**Comment by clewlb** [comment]
Please upgrade to our latest Android SDK at https://github.com/MOLPay/molpay-mobile-xdk-android
