### ISSUE TITLE
Wondering why "Password" and "VerifyKey" are required to use the SDK?

### ISSUE THREAD

**Issue by ryusoft** [MOLPay/Mobile_SDK-Android#7]
by putting Password and VerifyKey inside the source code? is it means that any one may potentially get the android apk, and decompile, then to view them in plain text? for me this is consider quite insecure, correct me if I am wrong.

or the "username", "password", and "verify key" is different with the one use on web api?

Imaging if they are same, then who get those info can login to the merchant portal and many information is leaked.

Why not consistently using the same method as the web api? that have the secretly generated "vcode", which maybe get from our "API", so by this way, password and verifyKey won't leak.

**Comment by arifjusohMOLPay** [comment]
Hi ryusoft, you're right. It is quite insecure to have Verify key inside the code. 
MOLPay do have solution for this
Have a look in chapter 3.10 Secure Mode
https://github.com/MOLPay/Mobile_SDK-Android/blob/master/MOLPay_SDK_android_4.4.0.pdf

Fyi sir, the username & password is not the same username and password you use to login to merchant portal. Its the API username and password, which will be given upon request to our support.

**Comment by ryusoft** [comment]
Okay, if the username and password are different, then should be okay. 

What about the verify key? i hope the verify key is different with the one on web, else potentially can fake out payment confirmation to out callback url as the vkey is leaked on the apps.

But I would suggest to have a place at portal there to let customer add and remove / change the information, for example, we can add "app", and assign username/password, and regenerate new vkey etc. 

BTW, about the secure mode, the verify key used is the one set in our merchant portal? or the one same with the "api" version? or all vkey refer to same vkey?

**Comment by arifjusohMOLPay** [comment]
Hi ryusoft,

> What about the verify key? i hope the verify key is different with the one on web, else potentially can fake out payment confirmation to out callback url as the vkey is leaked on the apps.

The verify key is the same with the one used in the Web. However by using secure mode, the verify key no longer added/leaked in the app. We advice create the <i>VCODE</i> in merchant server side.

> But I would suggest to have a place at portal there to let customer add and remove / change the information, for example, we can add "app", and assign username/password, and regenerate new vkey etc.

MOLPay don't provide the option to modified <b>AppName</b> & <b>VerifyKey</b> in portal for security reason. But You may request for changes to our support. 
However it is not recomended to change verify key as it will effect your current integration. But its still possible if you see it fits.

>BTW, about the secure mode, the verify key used is the one set in our merchant portal? or the one same with the "api" version? or all vkey refer to same vkey?

Im assuming you are referring to the example in the Doc "//Formula to generate vcode"
VERIFY KEY is the one inside the Merchant Profile -> "Verify Key"
